version: "2"
services:

  mailserver:
    build:
      context: ./mail
    ports:
      - "143:143"
      - "110:110"
    environment:
      - HOSTNAME=${HOSTNAME:-mailserver}
      - USERNAME=${HOSTNAME:-johnmcdnl}
      - PASSWORD=${HOSTNAME:-password}

  application:
    build:
      context: ./app
    restart: on-failure
    depends_on:
      - mailserver
    environment:
      - HOSTNAME=${HOSTNAME:-mailserver}
      - PORT=${HOSTNAME:-25}
      - USERNAME=${HOSTNAME:-johnmcdnl}
      - PASSWORD=${HOSTNAME:-password}

  reader:
    build:
      context: ./client
    restart: on-failure
    depends_on:
      - mailserver
    environment:
      - HOSTNAME=${HOSTNAME:-mailserver}
      - PORT=${HOSTNAME:-143}
      - USERNAME=${HOSTNAME:-johnmcdnl}
      - PASSWORD=${HOSTNAME:-password}
